#!/usr/bin/env python3
"""Shared per-city data for the lead-magnet guides + their city-page sidebar CTAs.
Add a city here (accurate facts; price tiers per CLAUDE.md, ranges not exacts),
then re-run build_city_guides.py and inject_city_guides.py."""

CITIES = {
 # ── flagship 8 ──
 "carmel": dict(name="Carmel", county="Hamilton County", url="/cities/hamilton-county/carmel-indiana-real-estate/",
   price="the mid-$400s to well over $1 million",
   schools="the highly regarded Carmel Clay Schools",
   areas=["the walkable Arts &amp; Design District", "the Village of WestClay", "West Carmel and the Clay Terrace area", "established golf communities like Bridgewater and Brookshire"],
   commute="roughly 20 minutes to downtown Indianapolis via US-31/Meridian Street and Keystone Parkway",
   character="an upscale, amenity-rich suburb famous for its roundabouts, the Palladium concert hall, the Monon Trail, and a genuinely walkable downtown"),
 "fishers": dict(name="Fishers", county="Hamilton County", url="/cities/hamilton-county/fishers-indiana-real-estate/",
   price="the low $300s to the $600s and beyond",
   schools="Hamilton Southeastern Schools",
   areas=["the vibrant Nickel Plate District", "waterfront living around Geist Reservoir", "established neighborhoods like Sunblest and Brooks Chase", "newer developments near Fishers Marketplace"],
   commute="about 25 minutes to downtown Indianapolis via I-69 and SR-37",
   character="one of America's most-recognized 'best places to live' — family-friendly, safe, and anchored by a lively Nickel Plate District with its amphitheater and farmers market"),
 "greenwood": dict(name="Greenwood", county="Johnson County", url="/cities/johnson-county/greenwood-indiana-real-estate/",
   price="the $250s to the $450s",
   schools="Center Grove and Greenwood Community Schools",
   areas=["revitalized Old Town Greenwood", "the sought-after Center Grove area", "Stones Crossing and the west side", "newer subdivisions near Worthsville Road"],
   commute="around 15 minutes to downtown Indianapolis via I-65 and US-31",
   character="the south metro's fast-growing retail and dining hub, offering strong value, an active Old Town, and easy interstate access"),
 "noblesville": dict(name="Noblesville", county="Hamilton County", url="/cities/hamilton-county/noblesville-indiana-real-estate/",
   price="the $300s to the $600s",
   schools="Noblesville Schools",
   areas=["the historic downtown square", "waterfront communities on Morse Reservoir", "The Harbour and Sagamore", "newer growth along SR-32 and Pleasant Street"],
   commute="about 30 minutes to downtown Indianapolis via SR-37 and I-69",
   character="Hamilton County's historic county seat, blending a charming courthouse-square downtown with lakefront living and steady new growth"),
 "westfield": dict(name="Westfield", county="Hamilton County", url="/cities/hamilton-county/westfield-indiana-real-estate/",
   price="the $300s to the $600s",
   schools="Westfield Washington Schools",
   areas=["the growing downtown Grand Junction district", "luxury living at Chatham Hills", "Maple Village and Wood Wind", "family neighborhoods near Grand Park"],
   commute="roughly 30 minutes to downtown Indianapolis via US-31",
   character="home of the massive Grand Park Sports Campus and one of Indiana's fastest-growing cities, with a rapidly developing downtown"),
 "zionsville": dict(name="Zionsville", county="Boone County", url="/cities/boone-county/zionsville-indiana-real-estate/",
   price="the mid-$400s to over $1 million",
   schools="the top-rated Zionsville Community Schools",
   areas=["the historic brick-street Village", "the Holliday Farms golf community", "Stonegate and Austin Oaks", "wooded estates on the north and west sides"],
   commute="about 25 minutes to downtown Indianapolis via I-65 and Michigan Road",
   character="small-town luxury at its finest — a charming brick-paved Main Street, boutique shopping, wooded lots, and some of the state's best schools"),
 "avon": dict(name="Avon", county="Hendricks County", url="/cities/hendricks-county/avon-indiana-real-estate/",
   price="the $250s to the $450s",
   schools="Avon Community School Corporation",
   areas=["family subdivisions along US-36", "the Avon Town Hall Park area", "newer communities near Ronald Reagan Parkway", "established neighborhoods off County Road 100 N"],
   commute="about 25 minutes to downtown Indianapolis via US-36 (Rockville Road) and I-74",
   character="a fast-growing, family-first Hendricks County community known for strong schools, new shopping, and excellent value on the west side"),
 "brownsburg": dict(name="Brownsburg", county="Hendricks County", url="/cities/hendricks-county/brownsburg-indiana-real-estate/",
   price="the $250s to the $450s",
   schools="the well-regarded Brownsburg Community School Corporation",
   areas=["downtown Brownsburg and Arbuckle Acres", "newer subdivisions near SR-267", "the Northfield and Cardinal areas", "communities close to I-74"],
   commute="about 25 minutes to downtown Indianapolis via I-74",
   character="a welcoming west-side town with racing heritage, top-rated schools, and a growing downtown that keeps a genuine small-town feel"),
 # ── second tier ──
 "plainfield": dict(name="Plainfield", county="Hendricks County", url="/cities/hendricks-county/plainfield-indiana-real-estate/",
   price="the $230s to the $400s",
   schools="Plainfield Community School Corporation",
   areas=["neighborhoods near the US-40 corridor", "Saratoga and Carter's Grove", "communities close to the Metropolis shopping area", "newer development on the south side"],
   commute="about 25 minutes to downtown Indianapolis via I-70 and US-40",
   character="a thriving Hendricks County town known for the Metropolis shopping district, excellent parks and trails, and easy interstate and airport access"),
 "franklin": dict(name="Franklin", county="Johnson County", url="/cities/johnson-county/franklin-indiana-real-estate/",
   price="the $250s to the $400s",
   schools="Franklin Community Schools",
   areas=["the historic downtown square", "neighborhoods near Franklin College", "communities off King Street and Jefferson", "newer subdivisions on the north and east sides"],
   commute="about 30 minutes to downtown Indianapolis via I-65 and US-31",
   character="the Johnson County seat, with a beautifully restored courthouse-square downtown, the historic Artcraft Theatre, and a genuine small-town college-town feel"),
 "whitestown": dict(name="Whitestown", county="Boone County", url="/cities/boone-county/whitestown-indiana-real-estate/",
   price="the $250s to the $450s",
   schools="Zionsville Community Schools (parts in Lebanon)",
   areas=["the large Anson development", "Walker Farms and Maple Knoll", "newer communities near Whitestown Parkway", "neighborhoods close to I-65"],
   commute="about 25 minutes to downtown Indianapolis via I-65",
   character="one of the fastest-growing towns in Indiana, anchored by the Anson mixed-use development, new schools, and quick interstate access"),
 "mccordsville": dict(name="McCordsville", county="Hancock County", url="/cities/hancock-county/mccordsville-indiana-real-estate/",
   price="the $280s to the $500s",
   schools="Mt. Vernon Community School Corporation",
   areas=["Emerald Springs and Gateway Crossing", "newer communities near SR-67", "the growing McCord Square town center", "family subdivisions off Broadway"],
   commute="about 25 minutes to downtown Indianapolis via I-69 and Fall Creek Road",
   character="Hancock County's fastest-growing town, offering newer construction, strong schools, and a brand-new walkable town center at McCord Square"),
 "southport": dict(name="Southport", county="Marion County", url="/cities/marion-county/southport-indiana-real-estate/",
   price="the $150s to the $320s",
   schools="Perry Township Schools",
   areas=["established neighborhoods around Southport Road", "communities near the city park", "the greater south side", "areas close to US-31 and I-65"],
   commute="about 15 minutes to downtown Indianapolis via US-31 and I-65",
   character="a small, tight-knit city on Indianapolis's south side offering affordable homes, a genuine community feel, and an easy commute"),
 "lawrence": dict(name="Lawrence", county="Marion County", url="/cities/marion-county/lawrence-indiana-real-estate/",
   price="the $150s to the $320s",
   schools="the MSD of Lawrence Township",
   areas=["the Fort Harrison and Fort Ben area", "Oaklandon", "established northeast-side neighborhoods", "communities near Pendleton Pike"],
   commute="about 20 minutes to downtown Indianapolis via I-465 and Pendleton Pike",
   character="a northeast-side city built around historic Fort Harrison State Park and the Fort Ben cultural campus, with affordable homes and green space"),
 "speedway": dict(name="Speedway", county="Marion County", url="/cities/marion-county/speedway-indiana-real-estate/",
   price="the $150s to the $320s",
   schools="the School Town of Speedway",
   areas=["the revitalized Main Street district", "neighborhoods near the Motor Speedway", "established mid-century streets", "communities close to I-465"],
   commute="about 15 minutes to downtown Indianapolis via I-465 and Crawfordsville Road",
   character="the home of the Indianapolis Motor Speedway — a walkable, revitalized town with a lively Main Street and unbeatable west-side access"),
 "lebanon": dict(name="Lebanon", county="Boone County", url="/cities/boone-county/lebanon-indiana-real-estate/",
   price="the $230s to the $400s",
   schools="Lebanon Community School Corporation",
   areas=["the historic downtown square", "established in-town neighborhoods", "newer subdivisions near I-65", "communities along SR-39"],
   commute="about 35 minutes to downtown Indianapolis via I-65",
   character="the Boone County seat with a classic courthouse-square downtown, affordable homes, and major growth on the horizon from the nearby LEAP innovation district"),
 "mooresville": dict(name="Mooresville", county="Morgan County", url="/cities/morgan-county/mooresville-indiana-real-estate/",
   price="the $200s to the $380s",
   schools="the Mooresville Consolidated School Corporation",
   areas=["the historic downtown", "neighborhoods near Pioneer Park", "communities along SR-67", "newer subdivisions on the north side"],
   commute="about 25 minutes to downtown Indianapolis via SR-67 and I-70",
   character="a friendly southwest-metro town with small-town charm, a walkable downtown, strong schools, and quick access to the interstate"),
 "danville": dict(name="Danville", county="Hendricks County", url="/cities/hendricks-county/danville-indiana-real-estate/",
   price="the $230s to the $400s",
   schools="the Danville Community School Corporation",
   areas=["the historic courthouse square", "established in-town neighborhoods", "newer communities off US-36", "areas near Ellis Park"],
   commute="about 30 minutes to downtown Indianapolis via US-36 and I-74",
   character="the Hendricks County seat, known for its picturesque courthouse square, the Mayberry Cafe, small-town charm, and highly regarded schools"),
 "shelbyville": dict(name="Shelbyville", county="Shelby County", url="/cities/shelby-county/shelbyville-indiana-real-estate/",
   price="the $150s to the $300s",
   schools="Shelbyville Central Schools",
   areas=["the downtown square and Blue River area", "established in-town neighborhoods", "newer communities near I-74", "areas along SR-9"],
   commute="about 35 minutes to downtown Indianapolis via I-74",
   character="the Shelby County seat offering some of the metro's most affordable homes, a revitalizing downtown on the Blue River, and easy interstate access"),
}
