#!/usr/bin/env python3
"""Auto-link glossary terms on first mention in body prose, site-wide.

Safety rules:
  * only rewrites text INSIDE <p> blocks (never headings/title/meta/schema)
  * never touches text inside an existing <a> (no nested anchors)
  * links only the FIRST mention of each term per page
  * caps NEW links per page (CAP_NEW) and total glossary links (MAX_TOTAL)
  * skips a term whose glossary URL is already linked on the page
  * word-boundary matches only; single left-to-right pass (never matches inside
    a just-inserted anchor)
  * skips /glossary/ and /agents/ (both regenerated by their own scripts)
  * inserts anchors only -> no whitespace/structure reflow
"""
import os, re, sys

ROOT = os.path.abspath(sys.argv[1]) if len(sys.argv) > 1 else "."
APPLY = "--apply" in sys.argv
CAP_NEW = 4
MAX_TOTAL = 6

# (variant phrase, glossary slug, case_sensitive). Variants sharing a slug dedupe by URL.
TERMS_RAW = [
 ("comparative market analysis", "comparative-market-analysis", False),
 ("private mortgage insurance", "private-mortgage-insurance", False),
 ("buyer's agency agreement", "buyers-agency-agreement", False),
 ("buyer’s agency agreement", "buyers-agency-agreement", False),
 ("buyer agency agreement", "buyers-agency-agreement", False),
 ("homeowners association", "hoa", False),
 ("seller's disclosure", "sellers-disclosure", False),
 ("seller’s disclosure", "sellers-disclosure", False),
 ("sellers disclosure", "sellers-disclosure", False),
 ("seller disclosure", "sellers-disclosure", False),
 ("homestead exemption", "homestead-exemption", False),
 ("homestead deduction", "homestead-exemption", False),
 ("property tax caps", "property-tax-caps", False),
 ("property tax cap", "property-tax-caps", False),
 ("final walk-through", "final-walk-through", False),
 ("final walk through", "final-walk-through", False),
 ("final walkthrough", "final-walk-through", False),
 ("conventional loans", "conventional-loan", False),
 ("conventional loan", "conventional-loan", False),
 ("home inspections", "home-inspection", False),
 ("home inspection", "home-inspection", False),
 ("home appraisals", "home-appraisal", False),
 ("home appraisal", "home-appraisal", False),
 ("appraisal gap", "appraisal-gap", False),
 ("earnest money", "earnest-money", False),
 ("title insurance", "title-insurance", False),
 ("days on market", "days-on-market", False),
 ("home equity", "home-equity", False),
 ("closing day", "closing-day", False),
 ("pre-qualification", "pre-approval-vs-pre-qualification", False),
 ("prequalification", "pre-approval-vs-pre-qualification", False),
 ("pre-approval", "pre-approval-vs-pre-qualification", False),
 ("preapproval", "pre-approval-vs-pre-qualification", False),
 ("as-is sale", "as-is-sale", False),
 ("contingencies", "contingency", False),
 ("contingency", "contingency", False),
 ("amortization", "amortization", False),
 ("escrow", "escrow", False),
 ("HOA", "hoa", True),
 ("adjustable-rate mortgage", "adjustable-rate-mortgage", False),
 ("closing disclosure", "closing-disclosure", False),
 ("fixed-rate mortgage", "fixed-rate-mortgage", False),
 ("loan estimate", "loan-estimate", False),
 ("annual percentage rate", "annual-percentage-rate", False),
 ("discount points", "discount-points", False),
 ("rate lock", "rate-lock", False),
 ("debt-to-income ratio", "debt-to-income-ratio", False),
 ("loan-to-value ratio", "loan-to-value-ratio", False),
 ("home equity line of credit", "home-equity-line-of-credit", False),
 ("jumbo loan", "jumbo-loan", False),
 ("mortgage broker", "mortgage-broker", False),
 ("mortgage lender", "mortgage-lender", False),
 ("prepayment penalty", "prepayment-penalty", False),
 ("rate cap", "rate-cap", False),
 ("purchase agreement", "purchase-agreement", False),
 ("escalation clause", "escalation-clause", False),
 ("contingency period", "contingency-period", False),
 ("financing contingency", "financing-contingency", False),
 ("inspection contingency", "inspection-contingency", False),
 ("appraisal contingency", "appraisal-contingency", False),
 ("proof of funds", "proof-of-funds", False),
 ("earnest money receipt", "earnest-money-receipt", False),
 ("seller concessions", "seller-concessions", False),
 ("option period", "option-period", False),
 ("earnest money dispute", "earnest-money-dispute", False),
 ("radon testing", "radon-testing", False),
 ("wood-destroying insect inspection", "wood-destroying-insect-inspection", False),
 ("reconsideration of value", "reconsideration-of-value", False),
 ("gross living area", "gross-living-area", False),
 ("well and septic inspection", "well-and-septic-inspection", False),
 ("lead-based paint disclosure", "lead-based-paint-disclosure", False),
 ("title search", "title-search", False),
 ("quitclaim deed", "quitclaim-deed", False),
 ("warranty deed", "warranty-deed", False),
 ("chain of title", "chain-of-title", False),
 ("title commitment", "title-commitment", False),
 ("deed restriction", "deed-restriction", False),
 ("joint tenancy", "joint-tenancy", False),
 ("tenancy by the entirety", "tenancy-by-the-entirety", False),
 ("cash to close", "cash-to-close", False),
 ("recording fees", "recording-fees", False),
 ("transfer tax", "transfer-tax", False),
 ("settlement statement", "settlement-statement", False),
 ("title company", "title-company", False),
 ("closing wire fraud", "closing-wire-fraud", False),
 ("listing agreement", "listing-agreement", False),
 ("exclusive right to sell", "exclusive-right-to-sell", False),
 ("price per square foot", "price-per-square-foot", False),
 ("list-to-sale ratio", "list-to-sale-ratio", False),
 ("absorption rate", "absorption-rate", False),
 ("assessed value", "assessed-value", False),
 ("mill rate", "mill-rate", False),
 ("capital gains tax", "capital-gains-tax", False),
 ("capital gains exclusion", "capital-gains-exclusion", False),
 ("sales disclosure form", "sales-disclosure-form", False),
 ("builder allowance", "builder-allowance", False),
 ("spec home", "spec-home", False),
 ("model home", "model-home", False),
 ("punch list", "punch-list", False),
 ("certificate of occupancy", "certificate-of-occupancy", False),
 ("builder warranty", "builder-warranty", False),
 ("lot premium", "lot-premium", False),
 ("upgrades and options", "upgrades-and-options", False),
 ("capitalization rate", "capitalization-rate", False),
 ("cash flow", "cash-flow", False),
 ("gross rent multiplier", "gross-rent-multiplier", False),
 ("after repair value", "after-repair-value", False),
 ("house hacking", "house-hacking", False),
 ("1031 exchange", "1031-exchange", False),
 ("cash-on-cash return", "cash-on-cash-return", False),
 ("net operating income", "net-operating-income", False),
 ("fix and flip", "fix-and-flip", False),
 ("planned unit development", "planned-unit-development", False),
 ("special assessment", "special-assessment", False),
 ("reserve fund", "reserve-fund", False),
 ("resale certificate", "resale-certificate", False),
 ("dual agency", "dual-agency", False),
 ("limited agency", "limited-agency", False),
 ("transaction coordinator", "transaction-coordinator", False),
 ("fiduciary duty", "fiduciary-duty", False),
 ("DTI", "debt-to-income-ratio", True),
 ("LTV", "loan-to-value-ratio", True),
 ("APR", "annual-percentage-rate", True),
 ("PITI", "piti", True),
 ("HELOC", "home-equity-line-of-credit", True),
 ("PUD", "planned-unit-development", True),
 ("NOI", "net-operating-income", True),
 ("GRM", "gross-rent-multiplier", True),
 ("ARV", "after-repair-value", True),
]
# longest phrases first so specific matches win
TERMS = sorted(TERMS_RAW, key=lambda t: -len(t[0]))

TAG = re.compile(r"<[^>]+>")
P_BLOCK = re.compile(r"<p\b[^>]*>.*?</p>", re.DOTALL | re.IGNORECASE)
# Match a full <p>…</p> block, OR a bare <a>/</a> tag, so we can track whether a
# <p> sits inside an outer anchor (e.g. a whole-card <a> wrapper) and skip it —
# linking inside an outer <a> would create invalid nested anchors that break layout.
BLOCK_OR_A = re.compile(
    r"(?P<p><p\b[^>]*>.*?</p>)|(?P<aopen><a\b[^>]*>)|(?P<aclose></a\s*>)",
    re.DOTALL | re.IGNORECASE)

def alnum(c):
    return c.isalnum() or c == "_"

def link_text(text, state):
    """Single left-to-right pass over a raw-text run; returns linked text."""
    out = []
    i, n = 0, len(text)
    while i < n:
        hit = None
        if state["new"] < CAP_NEW and (len(state["urls"]) + state["new"]) < MAX_TOTAL:
            for phrase, slug, cs in TERMS:
                url = "/glossary/%s/" % slug
                if url in state["urls"]:
                    continue
                L = len(phrase)
                seg = text[i:i+L]
                ok = (seg == phrase) if cs else (seg.lower() == phrase.lower())
                if not ok:
                    continue
                # word boundaries
                if i > 0 and alnum(text[i-1]):
                    continue
                if i+L < n and alnum(text[i+L]):
                    continue
                hit = (seg, url)
                break
        if hit:
            seg, url = hit
            out.append('<a href="%s" class="gloss-link">%s</a>' % (url, seg))
            state["urls"].add(url)
            state["new"] += 1
            i += len(seg)
        else:
            out.append(text[i])
            i += 1
    return "".join(out)

def process_p(block, state):
    m = re.match(r"(<p\b[^>]*>)(.*)(</p>)", block, re.DOTALL | re.IGNORECASE)
    if not m:
        return block
    open_t, inner, close_t = m.groups()
    parts = re.split(r"(<[^>]+>)", inner)
    depth = 0
    for k, tok in enumerate(parts):
        if TAG.fullmatch(tok or ""):
            low = tok.lower()
            if low.startswith("<a") and not low.startswith("</a"):
                depth += 1
            elif low.startswith("</a"):
                depth = max(0, depth - 1)
            continue
        if tok and depth == 0:
            parts[k] = link_text(tok, state)
    return open_t + "".join(parts) + close_t

def process_file(path):
    src = open(path, encoding="utf-8").read()
    existing = set(re.findall(r'href="(/glossary/[^"]+)"', src))
    state = {"urls": set(existing), "new": 0}
    # Single pass over the document, tracking anchor depth. Only <p> blocks at
    # depth 0 (not wrapped by an outer <a>, e.g. a card link) get linkified.
    out_parts = []
    last = 0
    a_depth = 0
    for m in BLOCK_OR_A.finditer(src):
        out_parts.append(src[last:m.start()])
        last = m.end()
        kind = m.lastgroup
        if kind == "p":
            block = m.group("p")
            out_parts.append(process_p(block, state) if a_depth == 0 else block)
        elif kind == "aopen":
            a_depth += 1
            out_parts.append(m.group("aopen"))
        else:  # aclose
            a_depth = max(0, a_depth - 1)
            out_parts.append(m.group("aclose"))
    out_parts.append(src[last:])
    out = "".join(out_parts)
    if out != src:
        # sanity: anchors still balanced
        if out.count("<a ") != out.count("</a>"):
            print("!! SKIP (unbalanced anchors):", path)
            return 0
        if APPLY:
            open(path, "w", encoding="utf-8").write(out)
    return state["new"]

def main():
    total_files = 0
    total_links = 0
    per_slug = {}
    for dp, dn, fn in os.walk(ROOT):
        rel = os.path.relpath(dp, ROOT)
        if "/.git" in dp or rel.startswith(".git"):
            continue
        parts = rel.split(os.sep)
        if "glossary" in parts or "agents" in parts:
            continue
        for f in fn:
            if not f.endswith(".html"):
                continue
            path = os.path.join(dp, f)
            before = open(path, encoding="utf-8").read()
            added = process_file(path)
            if added:
                total_files += 1
                total_links += added
                after = open(path, encoding="utf-8").read() if APPLY else None
                if APPLY:
                    for u in re.findall(r'href="(/glossary/[^"]+)" class="gloss-link"', after):
                        per_slug[u] = per_slug.get(u, 0) + 1
    mode = "APPLIED" if APPLY else "DRY-RUN"
    print("[%s] files touched: %d   new glossary links: %d" % (mode, total_files, total_links))
    if per_slug:
        print("per-term (applied):")
        for u, c in sorted(per_slug.items(), key=lambda x: -x[1]):
            print("  %4d  %s" % (c, u))

if __name__ == "__main__":
    main()
