#!/usr/bin/env python3
"""Auto-link glossary terms on first mention in body prose, site-wide.

Safety rules:
  * only rewrites text INSIDE <p> blocks (never headings/title/meta/schema)
  * never touches text inside an existing <a> (no nested anchors)
  * links only the FIRST mention of each term per page
  * caps NEW links per page (CAP_NEW) and total glossary links (MAX_TOTAL)
  * skips a term whose glossary URL is already linked on the page
  * word-boundary matches only; single left-to-right pass (never matches inside
    a just-inserted anchor)
  * skips /glossary/ and /agents/ (both regenerated by their own scripts)
  * inserts anchors only -> no whitespace/structure reflow
"""
import os, re, sys

ROOT = os.path.abspath(sys.argv[1]) if len(sys.argv) > 1 else "."
APPLY = "--apply" in sys.argv
CAP_NEW = 4
MAX_TOTAL = 6

# (variant phrase, glossary slug, case_sensitive). Variants sharing a slug dedupe by URL.
TERMS_RAW = [
 ("comparative market analysis", "comparative-market-analysis", False),
 ("private mortgage insurance", "private-mortgage-insurance", False),
 ("buyer's agency agreement", "buyers-agency-agreement", False),
 ("buyer’s agency agreement", "buyers-agency-agreement", False),
 ("buyer agency agreement", "buyers-agency-agreement", False),
 ("homeowners association", "hoa", False),
 ("seller's disclosure", "sellers-disclosure", False),
 ("seller’s disclosure", "sellers-disclosure", False),
 ("sellers disclosure", "sellers-disclosure", False),
 ("seller disclosure", "sellers-disclosure", False),
 ("homestead exemption", "homestead-exemption", False),
 ("homestead deduction", "homestead-exemption", False),
 ("property tax caps", "property-tax-caps", False),
 ("property tax cap", "property-tax-caps", False),
 ("final walk-through", "final-walk-through", False),
 ("final walk through", "final-walk-through", False),
 ("final walkthrough", "final-walk-through", False),
 ("conventional loans", "conventional-loan", False),
 ("conventional loan", "conventional-loan", False),
 ("home inspections", "home-inspection", False),
 ("home inspection", "home-inspection", False),
 ("home appraisals", "home-appraisal", False),
 ("home appraisal", "home-appraisal", False),
 ("appraisal gap", "appraisal-gap", False),
 ("earnest money", "earnest-money", False),
 ("title insurance", "title-insurance", False),
 ("days on market", "days-on-market", False),
 ("home equity", "home-equity", False),
 ("closing day", "closing-day", False),
 ("pre-qualification", "pre-approval-vs-pre-qualification", False),
 ("prequalification", "pre-approval-vs-pre-qualification", False),
 ("pre-approval", "pre-approval-vs-pre-qualification", False),
 ("preapproval", "pre-approval-vs-pre-qualification", False),
 ("as-is sale", "as-is-sale", False),
 ("contingencies", "contingency", False),
 ("contingency", "contingency", False),
 ("amortization", "amortization", False),
 ("escrow", "escrow", False),
 ("HOA", "hoa", True),
]
# longest phrases first so specific matches win
TERMS = sorted(TERMS_RAW, key=lambda t: -len(t[0]))

TAG = re.compile(r"<[^>]+>")
P_BLOCK = re.compile(r"<p\b[^>]*>.*?</p>", re.DOTALL | re.IGNORECASE)

def alnum(c):
    return c.isalnum() or c == "_"

def link_text(text, state):
    """Single left-to-right pass over a raw-text run; returns linked text."""
    out = []
    i, n = 0, len(text)
    while i < n:
        hit = None
        if state["new"] < CAP_NEW and (len(state["urls"]) + state["new"]) < MAX_TOTAL:
            for phrase, slug, cs in TERMS:
                url = "/glossary/%s/" % slug
                if url in state["urls"]:
                    continue
                L = len(phrase)
                seg = text[i:i+L]
                ok = (seg == phrase) if cs else (seg.lower() == phrase.lower())
                if not ok:
                    continue
                # word boundaries
                if i > 0 and alnum(text[i-1]):
                    continue
                if i+L < n and alnum(text[i+L]):
                    continue
                hit = (seg, url)
                break
        if hit:
            seg, url = hit
            out.append('<a href="%s" class="gloss-link">%s</a>' % (url, seg))
            state["urls"].add(url)
            state["new"] += 1
            i += len(seg)
        else:
            out.append(text[i])
            i += 1
    return "".join(out)

def process_p(block, state):
    m = re.match(r"(<p\b[^>]*>)(.*)(</p>)", block, re.DOTALL | re.IGNORECASE)
    if not m:
        return block
    open_t, inner, close_t = m.groups()
    parts = re.split(r"(<[^>]+>)", inner)
    depth = 0
    for k, tok in enumerate(parts):
        if TAG.fullmatch(tok or ""):
            low = tok.lower()
            if low.startswith("<a") and not low.startswith("</a"):
                depth += 1
            elif low.startswith("</a"):
                depth = max(0, depth - 1)
            continue
        if tok and depth == 0:
            parts[k] = link_text(tok, state)
    return open_t + "".join(parts) + close_t

def process_file(path):
    src = open(path, encoding="utf-8").read()
    existing = set(re.findall(r'href="(/glossary/[^"]+)"', src))
    state = {"urls": set(existing), "new": 0}
    def repl(mo):
        return process_p(mo.group(0), state)
    out = P_BLOCK.sub(repl, src)
    if out != src:
        # sanity: anchors still balanced
        if out.count("<a ") != out.count("</a>"):
            print("!! SKIP (unbalanced anchors):", path)
            return 0
        if APPLY:
            open(path, "w", encoding="utf-8").write(out)
    return state["new"]

def main():
    total_files = 0
    total_links = 0
    per_slug = {}
    for dp, dn, fn in os.walk(ROOT):
        rel = os.path.relpath(dp, ROOT)
        if "/.git" in dp or rel.startswith(".git"):
            continue
        parts = rel.split(os.sep)
        if "glossary" in parts or "agents" in parts:
            continue
        for f in fn:
            if not f.endswith(".html"):
                continue
            path = os.path.join(dp, f)
            before = open(path, encoding="utf-8").read()
            added = process_file(path)
            if added:
                total_files += 1
                total_links += added
                after = open(path, encoding="utf-8").read() if APPLY else None
                if APPLY:
                    for u in re.findall(r'href="(/glossary/[^"]+)" class="gloss-link"', after):
                        per_slug[u] = per_slug.get(u, 0) + 1
    mode = "APPLIED" if APPLY else "DRY-RUN"
    print("[%s] files touched: %d   new glossary links: %d" % (mode, total_files, total_links))
    if per_slug:
        print("per-term (applied):")
        for u, c in sorted(per_slug.items(), key=lambda x: -x[1]):
            print("  %4d  %s" % (c, u))

if __name__ == "__main__":
    main()
